apiVersion: v1
kind: Service
metadata:
  name: pmanual
  namespace: wmanual
spec:
  type: LoadBalancer
  selector:
    app: pmanual
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000